import 'dotenv/config';
import express from 'express';
import { GoogleGenAI } from '@google/genai';
import { createServer as createViteServer } from 'vite';
const app=express(); app.use(express.json({limit:'1mb'}));
const ai=process.env.GEMINI_API_KEY ? new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY}) : null;
const system=`You are Convertible Cranium AI, the conversational host of Convertible Cranium Operator OS. Help a person observe and understand their own cognition. Distinguish reported facts from interpretations and hypotheses. You may explain general psychology and psychoanalytic concepts educationally, but never present an AI inference as a clinical diagnosis. Ask thoughtful follow-up questions. Do not claim certainty about motives, disorders, or hidden mental states. If suggesting a pattern, give the evidence and invite correction. The user's agency is primary.`;
app.get('/api/health',(_,res)=>res.json({ok:true,product:'Convertible Cranium Operator OS',ai:!!ai}));
app.post('/api/chat',async(req,res)=>{const {message,history=[]}=req.body||{}; if(typeof message!=='string'||!message.trim()) return res.status(400).json({error:'message required'}); if(!ai) return res.json({reply:`I can work in local reflection mode. You said: “${message.trim()}”\n\nWhat were you noticing in yourself when that happened?`}); try {const contents=[...history.slice(-12).map((m:any)=>({role:m.role==='assistant'?'model':'user',parts:[{text:String(m.content)}]})),{role:'user',parts:[{text:message.trim()}]}]; const r=await ai.models.generateContent({model:'gemini-2.5-flash',contents,config:{systemInstruction:system,temperature:.45}}); res.json({reply:r.text||'I could not form a response.'});} catch(e){res.status(502).json({error:'AI request failed',detail:String(e)});} });
const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'}); app.use(vite.middlewares); app.listen(process.env.PORT||4170,()=>console.log('Cranium Mapper listening'));
