import { useMemo, useState } from 'react';
import { Brain, ChevronRight, CircleHelp, Eye, GitBranch, MessageCircle, Plus, ShieldCheck, Sparkles, X } from 'lucide-react';
import type { ChatMessage, Observation, Pattern } from './types';
import { derivePatterns, extractObservation } from './mapping';
import { loadObservations, loadPatterns, saveObservations, savePatterns } from './store';

export type ActiveView = 'chat' | 'map' | 'tracker' | 'studio' | 'metacognition' | 'diligence' | 'architecture' | 'canon' | 'benchmark' | 'memory' | 'settings';

const intro=`Convertible Cranium Operator OS helps you observe how your own cognition appears to work over time. You can journal, talk through decisions, examine reactions, and voluntarily let Cranium ask questions while you research or reflect. The Mapper builds hypotheses from your observations. It does not define who you are, and its psychological material is educational rather than a clinical diagnosis.`;

export default function App(){
 const [messages,setMessages]=useState<ChatMessage[]>([{role:'assistant',content:intro+"\n\nStart anywhere. Tell me what happened, what you were thinking, a decision you made, or something you've been noticing about yourself."}]);
 const [input,setInput]=useState(''); const [tab,setTab]=useState<'chat'|'map'|'tracker'>('chat');
 const [obs,setObs]=useState<Observation[]>(loadObservations); const [patterns,setPatterns]=useState<Pattern[]>(loadPatterns); const [adapting,setAdapting]=useState(false); const [observeMode,setObserveMode]=useState(false); const [busy,setBusy]=useState(false);
 const visiblePatterns=useMemo(()=>patterns.length?patterns:derivePatterns(obs),[patterns,obs]);
 const send=async()=>{const text=input.trim(); if(!text||busy)return; setInput(''); const next=[...messages,{role:'user' as const,content:text}]; setMessages(next); const o=extractObservation(text); const nextObs=[o,...obs]; setObs(nextObs); saveObservations(nextObs); const derived=derivePatterns(nextObs); setPatterns(derived); savePatterns(derived); setBusy(true); try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:messages})}); const data=await r.json(); setMessages(m=>[...m,{role:'assistant',content:data.reply||data.error||'I could not respond.'}]);}finally{setBusy(false);}};
 const confirmPattern=(p:Pattern,status:Pattern['status'])=>{const updated=patterns.map(x=>x.id===p.id?{...x,status}:x);setPatterns(updated);savePatterns(updated)};
 return <div className="min-h-screen text-slate-100"><header className="sticky top-0 z-20 border-b border-white/10 bg-[#080b11]/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3"><div className="flex items-center gap-3"><div className="rounded-xl border border-cyan-300/30 bg-cyan-300/10 p-2"><Brain size={20}/></div><div><div className="font-semibold tracking-tight">CONVERTIBLE CRANIUM OPERATOR OS</div><div className="text-[10px] uppercase tracking-[.22em] text-slate-500">observe · question · map · understand</div></div></div><button onClick={()=>setAdapting(v=>!v)} className={`rounded-full border px-3 py-1.5 text-xs ${adapting?'border-cyan-300/50 bg-cyan-300/10 text-cyan-200':'border-white/10 text-slate-400'}`}>Cognitive adaptation {adapting?'ON':'OFF'}</button></div></header>
 <main className="mx-auto grid max-w-6xl gap-4 p-4 lg:grid-cols-[1fr_320px]">
 <section className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.035] shadow-2xl"><div className="flex items-center gap-2 border-b border-white/10 p-2">{[['chat','Talk to Convertible Cranium AI'],['map','Cognitive Map'],['tracker','Tracker']] .map(([id,label])=><button key={id} onClick={()=>setTab(id as any)} className={`rounded-xl px-4 py-2 text-sm ${tab===id?'bg-white/10 text-white':'text-slate-500'}`}>{label}</button>)}</div>
 {tab==='chat'&&<><div className="h-[60vh] overflow-y-auto p-5 space-y-4">{messages.map((m,i)=><div key={i} className={`flex ${m.role==='user'?'justify-end':''}`}><div className={`max-w-[85%] whitespace-pre-wrap rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==='user'?'bg-cyan-300/10 border border-cyan-300/20':'bg-black/20 border border-white/10'}`}>{m.content}</div></div>)}{busy&&<div className="text-sm text-slate-500">Convertible Cranium AI is thinking...</div>}</div><div className="border-t border-white/10 p-3"><div className="mb-2 flex items-center gap-2 text-xs text-slate-500"><button onClick={()=>setObserveMode(v=>!v)} className={`flex items-center gap-1 rounded-full border px-2.5 py-1 ${observeMode?'border-cyan-300/40 text-cyan-200':'border-white/10'}`}><Eye size={13}/> {observeMode?'Observation mode on':'Ask Convertible Cranium AI to observe'}</button><span>Nothing is silently recorded from other apps in this build.</span></div><div className="flex gap-2"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Tell Cranium what happened, what you thought, or what you're trying to understand..." className="min-h-14 flex-1 resize-none rounded-2xl border border-white/10 bg-black/20 p-3 outline-none focus:border-cyan-300/40"/><button onClick={send} className="rounded-2xl bg-cyan-300 px-5 font-semibold text-slate-950"><ChevronRight/></button></div></div></>}
 {tab==='map'&&<MapView patterns={visiblePatterns} observations={obs} onConfirm={confirmPattern}/>} {tab==='tracker'&&<Tracker observations={obs} onAdd={(o)=>{const n=[o,...obs];setObs(n);saveObservations(n);const p=derivePatterns(n);setPatterns(p);savePatterns(p)}}/>}
 </section>
 <aside className="space-y-3"><Card icon={<Sparkles size={17}/>} title="What this is">A living, user-governed map of observed cognitive patterns. It is not a personality score.</Card><Card icon={<CircleHelp size={17}/>} title="Psychology layer">Convertible Cranium AI can explain general psychological and psychoanalytic concepts, then compare them with patterns you report. Similarity is not diagnosis.</Card><Card icon={<ShieldCheck size={17}/>} title="Authority boundary">Observations and hypotheses are not canonical authority. The production version should route durable state through Convertible Cranium's governed memory and Kernel.</Card><Card icon={<GitBranch size={17}/>} title="Adaptation">{adapting?'Convertible Cranium AI is configured to adapt communication to the patterns you have allowed it to learn.':'Standard Convertible Cranium AI personality is active. Adaptation remains off until you choose it.'}</Card></aside>
 </main></div>
}
function Card({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold">{icon}{title}</div><div className="text-xs leading-5 text-slate-500">{children}</div></div>}
function MapView({patterns,observations,onConfirm}:{patterns:Pattern[];observations:Observation[];onConfirm:(p:Pattern,s:Pattern['status'])=>void}){return <div className="p-5"><div className="mb-4"><div className="text-lg font-semibold">Your cognitive map</div><div className="text-sm text-slate-500">Patterns remain hypotheses until you review them.</div></div><div className="map-grid min-h-[58vh] rounded-3xl border border-white/10 p-6"><div className="flex min-h-[50vh] flex-col items-center justify-center gap-5"><div className="rounded-full border border-cyan-300/40 bg-cyan-300/10 px-5 py-3 text-sm">YOU · evolving cognitive map</div>{patterns.length===0?<div className="max-w-md text-center text-sm text-slate-500">Add a few observations through conversation or the tracker. Repeated themes will begin appearing here.</div>:<div className="grid w-full max-w-3xl gap-3 sm:grid-cols-2">{patterns.map(p=><div key={p.id} className="rounded-2xl border border-white/10 bg-[#0b0f17]/90 p-4"><div className="flex items-center justify-between"><span className="font-medium">{p.label}</span><span className="text-xs text-cyan-200">{Math.round(p.confidence*100)}%</span></div><p className="mt-2 text-xs leading-5 text-slate-500">{p.description}</p><div className="mt-2 text-[11px] text-slate-600">Evidence: {p.evidenceIds.length} observations</div>{p.status==='hypothesis'&&<div className="mt-3 flex gap-2"><button onClick={()=>onConfirm(p,'user_confirmed')} className="rounded-lg bg-white/10 px-2 py-1 text-xs">Confirm</button><button onClick={()=>onConfirm(p,'user_rejected')} className="rounded-lg bg-white/5 px-2 py-1 text-xs text-slate-500">Reject</button></div>}</div>)}</div>}{observations.length>0&&<div className="text-xs text-slate-600">{observations.length} observations informing this map.</div>}</div></div></div>}
function Tracker({observations,onAdd}:{observations:Observation[];onAdd:(o:Observation)=>void}){const [text,setText]=useState('');return <div className="p-5"><div className="mb-4"><div className="text-lg font-semibold">Metacognitive Tracker</div><div className="text-sm text-slate-500">A simple place to record what you noticed. Cranium can turn these observations into map candidates.</div></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="What happened? What were you thinking, feeling, deciding, avoiding, researching, or reconsidering?" className="min-h-40 w-full rounded-2xl border border-white/10 bg-black/20 p-4 outline-none"/><button disabled={!text.trim()} onClick={()=>{onAdd(extractObservation(text));setText('')}} className="mt-3 flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-30"><Plus size={16}/> Log observation</button><div className="mt-6 space-y-2">{observations.slice(0,12).map(o=><div key={o.id} className="rounded-xl border border-white/10 p-3"><div className="text-xs text-slate-600">{new Date(o.createdAt).toLocaleString()}</div><div className="mt-1 text-sm">{o.text}</div>{o.tags.length>0&&<div className="mt-2 flex flex-wrap gap-1">{o.tags.map(t=><span key={t} className="rounded-full bg-white/5 px-2 py-0.5 text-[10px] text-slate-500">{t}</span>)}</div>}</div>)}</div></div>}
